plugins:
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme

readme_index:
  enabled: false

remote_theme: pmarsceill/just-the-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - build_scripts
  - "*.bat"

markdown: kramdown
kramdown:
  parse_block_html: true

baseurl: "/foo_dotnet_component_host/" 
url: "https://theqwertiest.github.io"

permalink: pretty

title: .NET Component Host

aux_links:
  "View on GitHub":
    - "//github.com/theqwertiest/foo_dotnet_component_host"

color_scheme: "dark"

footer_content: "Copyright &copy; 2021 Yuri Shutenko.<br/>Distributed by an <a href=\"https://github.com/TheQwertiest/foo_dotnet_component_host/blob/master/LICENSE\">MIT license.</a>"

ga_tracking: G-RS9WMWWJ2R
